name: Deploy Deno to Azure App Service
description: Publish a Deno 🦕 web app to Azure App Service on Linux
inputs:
  app-name:
    description: Name of the Azure Web App
    required: true
  resource-group:
    description: Name of the resource group
    required: true
  package:
    description: Path to zip package to deploy
    required: true
  script-file:
    description: Path to script to pass to deno run
    required: true
  deno-version:
    description: Version of deno to use
    required: false
    default: latest
runs:
  using: node12
  main: dist/index.js